#!/bin/bash
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
MYIP=$(wget -qO- ifconfig.me/ip);
echo "Checking VPS"
clear
figlet BENGKEL VPS | lolcat -d 5
echo -e ""
echo -e "\e[1;32m═════════════════════════════════════════" | lolcat
echo -e "          \e[1;31m\e[1;31m═[\e[mBengkel VpS\e[1;31m]═\e[m" 
echo -e "\e[1;32m═════════════════════════════════════════" | lolcat
echo -e " 1\e[1;33m)\e[m  Block Torrent"
echo -e " 2\e[1;33m)\e[m  Bench Network"
echo -e " 3\e[1;33m)\e[m  Edit Banner Messege"
echo -e " 4\e[1;33m)\e[m  Log Limit Account"
echo -e " 5\e[1;33m)\e[m  Updatescript"
echo -e " 6\e[1;33m)\e[m  Delete Akun Expired"
echo -e " 7\e[1;33m)\e[m  Generate SSH"
echo -e " 8\e[1;33m)\e[m  User List"
echo -e " 9\e[1;33m)\e[m  User Lock"
echo -e " 10\e[1;33m)\e[m Ganti Password VPS"
echo -e " 11\e[1;33m)\e[m User Unlock"
echo -e ""
echo -e "\e[1;32m══════════════════════════════════════════" | lolcat
echo -e " x)   MENU"
echo -e "\e[1;32m══════════════════════════════════════════" | lolcat
echo -e ""
read -p "     Please Input Number  [1-10 or x] :  "  ambe
echo -e ""
case $ambe in
1)
antitorrent
;;
2)
bench-network
;;
3)
nano /etc/issue.net
;;
4)
log-limit
;;
5)
updatescript
;;
6)
user-delete-expired
;;
7)
user-generate
;;
8)
user-list
;;
9)
user-lock
;;
10)
user-password
;;
11)
user-unlock
;;
x)
exit
;;
*)
clear
menu
;;
esac
